[package]
name = "rust_try_lib"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = { version = "0.33.3+1.2.191", optional = true }
ash-window = { version = "0.7.0", optional = true }
winit = "0.25.0"
shaderc = "0.7.3"
image = { version = "0.23.14", default-features = false, features = ["png"] }
raw-window-handle = "0.3.3"

[features]
default = ["Vulkan"]
Vulkan = ["ash", "ash-window"]
